############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Our Work"
url = "/work"
weight = 2

[[main]]
name = "About"
url = "/about"
weight = 3

[[main]]
name = "Contact"
url = "/contact"
weight = 4


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Contact"
url = "/contact"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
