############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Our Work"
url = "/work"
weight = 2

[[main]]
name = "Resources"
url = "/resources"
weight = 3

[[main]]
name = "About"
url = "/about"
weight = 4


# footer menu

[[footer]]
name = "About"
url = "/about"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3